ruby_box/rails/belt_reviewer/reviewer/config/routes.rb
Rails.application.routes.draw do
  root 'users#new'

  # New User
  get   'register'      => 'users#new',         as: 'new_register'
  get   'users/new'     => 'users#new'
  # Create User
  post  'register'      => 'users#create',      as: 'register'
  post  'users'         => 'users#create'
  # Show User
  get   'users/:id'     => 'users#show',        as: 'user' 

  # New Login
  get   'login'         => 'sessions#new',      as: 'new_login'
  get   'sessions/new'  => 'sessions#new'
  # Login
  post  'login'         => 'sessions#create',   as: 'login'
  post  'sessions'      => 'sessions#create'
  # Logout
  delete    'logout'    => 'sessions#destroy',  as: 'logout'
  delete    'sessions'  => 'sessions#destroy'
  #------------------------------------------------------------------------------
  #Event Routes

  get 'events'          => 'events#index',      as: 'events'
  post 'events'         => 'events#create',     as: 'create_event'
end

ruby_box/rails/belt_reviewer/reviewer/app/models/application_record.rb
require 'date'

class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true

    def future_dated
        if date.present? && date < Date.today
            errors.add(:date, "can't be in the past.")
        end
    end
end

ruby_box/rails/belt_reviewer/reviewer/app/models/attend.rb
class Attend < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

ruby_box/rails/belt_reviewer/reviewer/app/models/event.rb
class Event < ActiveRecord::Base
    belongs_to :user
    
    has_many :messages

    has_many :attends
    has_many :attendees, through: :attends, source: :user

    validates :name, :city, presence: true, length: { in: 2..30 }

    validates :state, presence: true

    validate :future_dated
    #alternative is validates_timeliness gem

    # def future_dated
    #     if date.present? && date < Date.today
    #         errors.add(:date, "Cant be in the past.")
    #     end
    # end
end

ruby_box/rails/belt_reviewer/reviewer/app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :event

  validates :content, presence: true, length: { minimum: 2 }
end

ruby_box/rails/belt_reviewer/reviewer/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :events

  has_many :messages

  has_many :attends
  has_many :attending, through: :attends, source: :event

  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
  validates :first_name, :last_name, :city, :state, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: EMAIL_REGEX }

  before_save :email_lowercase

  def email_lowercase #make email lowercase before submission have to
    email.downcase!
  end
  
end

ruby_box/rails/belt_reviewer/reviewer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

ruby_box/rails/belt_reviewer/reviewer/app/controllers/attends_controller.rb
class AttendsController < ApplicationController
end

ruby_box/rails/belt_reviewer/reviewer/app/controllers/events_controller.rb
class EventsController < ApplicationController

    def index
        @events = Event.all
    end

    def create
        @event = Event.create(event_params)

        return redirect_to events_path if @event.valid?

        flash[:errors] = @event.errors.full_messages

        return redirect_back fallback_location: events_path
    end



    private
    def event_params
        params.require(:event).permit(:name, :date, :city, :state).merge(user:current_user)
    end
end

ruby_box/rails/belt_reviewer/reviewer/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

ruby_box/rails/belt_reviewer/reviewer/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new 
    #display the page for me to log in
    end 

    def create
        user =  User.find_by_email(params[:user][:email])

        if user
            if user.try(:authenticate, params[:user][:password])
                session[:user_id] = user.id

                return redirect_to events_path
            end
            flash[:errors] = ["Password is not correct"]
        else
            flash[:errors] = ["Account not found."]
        end
        return redirect_to :back
    end 

    def destroy
        session.delete(:user_id) if session[:user_id]

        return redirect_to new_login_path
    end
end

ruby_box/rails/belt_reviewer/reviewer/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new

    end 


    def create
        user = User.create(user_params)

        if user.valid?
            session[:user_id] = user.id
            return redirect_to events_path
        end


        else
            flash[:errors] = user.errors.full_messages
            return redirect_to :back
    end 


    def show
        @user= User.find(params[:id])
    end



    private
    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :city, :state, :password, :password_confirmation)
    end
end

ruby_box/rails/belt_reviewer/reviewer/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby_box/rails/belt_reviewer/reviewer/app/helpers/attends_helper.rb
module AttendsHelper
end

ruby_box/rails/belt_reviewer/reviewer/app/helpers/events_helper.rb
module EventsHelper
end

ruby_box/rails/belt_reviewer/reviewer/app/helpers/messages_helper.rb
module MessagesHelper
end

ruby_box/rails/belt_reviewer/reviewer/app/helpers/sessions_helper.rb
module SessionsHelper
end

ruby_box/rails/belt_reviewer/reviewer/app/helpers/user_helper.rb
module UserHelper
end

ruby_box/rails/belt_reviewer/reviewer/app/helpers/users_helper.rb
module UsersHelper
end

ruby_box/rails/belt_reviewer/reviewer/app/views/events/index.html.erb
<h2>Welcome, <%= current_user.first_name %>!</h2>
<%
=begin%>
All Events in Our State
<%
=end%>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Date</th>
            <th>Location</th>
            <th>Post</th>
            <th>Action/Status</th>
        </tr>
    </thead>
    <tbody>
    <% @events.each do |event| %>
        <tr>
            <td> <%= event.name %> </td>
            <td> <%= event.date %> </td>
            <td> <%= event.city %> </td>
            <td> <%= event.user.first_name %> </td>
            <td>
                <!-- Actions -->

            </td>
        </tr>
    <% end %>
    </tbody>
</table>




    <div class="register">
        <div class="row">
            <div class="col-mid-12">
                <h5>Add Event</h5>
                <form action="<%= create_event_path %>" method="POST">
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
                    <div class="form-group">
                        <label for="Name">Name</label>
                        <input type="text" class="form-control" id="name" aria-describedby="name" name="event[name]">
                    </div>
                    <div class="form-group">
                        <label for="date">Date</label>
                        <input type="date" class="form-control" id="date" aria-describedby="date" name="event[date]">
                    </div>
                    <div class="form-group" style="display: inline-block;">
                        <label for="location">Location</label>
                        <input type="text" class="form-control" id="location" aria-describedby="locationHelp" name="event[city]">
                    </div>
                    <div style="display: inline-block;">
                        <label for="validationCustom04">State</label>
                        <select class="custom-select" id="validationCustom04" name="user[state]">
                            <option selected disabled value="">Choose...</option>
                            <option>...</option>
                            <option value="AL">AL</option>
                            <option value="AK">AK</option>
                            <option value="AR">AR</option>	
                            <option value="AZ">AZ</option>
                            <option value="CA">CA</option>
                            <option value="CO">CO</option>
                            <option value="CT">CT</option>
                            <option value="DC">DC</option>
                            <option value="DE">DE</option>
                            <option value="FL">FL</option>
                            <option value="GA">GA</option>
                            <option value="HI">HI</option>
                            <option value="IA">IA</option>	
                            <option value="ID">ID</option>
                            <option value="IL">IL</option>
                            <option value="IN">IN</option>
                            <option value="KS">KS</option>
                            <option value="KY">KY</option>
                            <option value="LA">LA</option>
                            <option value="MA">MA</option>
                            <option value="MD">MD</option>
                            <option value="ME">ME</option>
                            <option value="MI">MI</option>
                            <option value="MN">MN</option>
                            <option value="MO">MO</option>	
                            <option value="MS">MS</option>
                            <option value="MT">MT</option>
                            <option value="NC">NC</option>	
                            <option value="NE">NE</option>
                            <option value="NH">NH</option>
                            <option value="NJ">NJ</option>
                            <option value="NM">NM</option>			
                            <option value="NV">NV</option>
                            <option value="NY">NY</option>
                            <option value="ND">ND</option>
                            <option value="OH">OH</option>
                            <option value="OK">OK</option>
                            <option value="OR">OR</option>
                            <option value="PA">PA</option>
                            <option value="RI">RI</option>
                            <option value="SC">SC</option>
                            <option value="SD">SD</option>
                            <option value="TN">TN</option>
                            <option value="TX">TX</option>
                            <option value="UT">UT</option>
                            <option value="VT">VT</option>
                            <option value="VA">VA</option>
                            <option value="WA">WA</option>
                            <option value="WI">WI</option>	
                            <option value="WV">WV</option>
                            <option value="WY">WY</option>
                        </select>
                        <div class="invalid-feedback">
                            Please select a valid state.
                        </div>
                    </div>
                    <div class="form_group" >
                        <button type="submit" class="btn btn-secondary">Add Event!</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

ruby_box/rails/belt_reviewer/reviewer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reviewer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="<%= root_path %>">Homepage</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
        <% if current_user %>
          <li class="nav-item active">
            <a class="nav-link" href="<%= logout_path %>" data-method="delete">Logout <span class="sr-only">(current)</span></a>
            <% else %>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= new_register_path %>">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= new_login_path %>">Login</a>
          </li>
          <% end %>
        </ul>
      </div>
    </nav>

  <div class="container">
    
    <!-- ERRORS  -->
    <% if flash[:errors] %>
      <% flash[:errors].each do |error| %>
        <ul>
          <li class="text-danger"> <%= error %> </li>
        </ul>
      <% end %>
    <% end %>
      <%= yield %>

  </div>

</body>
</html>